config/routes.rb
Rails.application.routes.draw do
 
  get 'sales/index'
  get 'sales/show'
  devise_for :users
  root 'pages#home'
  # root :to => 'products#index'
  

  resources :users do 
    resource :profile
    resources :orders, only: [:index, :show]
    resources :users, only: [:show, :index]
  end
  # resources :users, only: [:show, :index]
  resources :profiles, only: [:index, :show, :create]
  resources :products
  get 'my_products', to: 'products#my_products' 
  get 'search_product', to: 'products#search'
  resources :categories
  resources :orders
  #resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]
  
  get "*path", to: redirect('/')
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    current_user.add_to_cart(params[:product_id])
    flash[:info] = "Are your Delivery Details Correct?"
    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    if current_user.cart_count < 1
      redirect_to products_path
    else
      redirect_to cart_path
    end
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end

end

app/views/carts/show.html.erb
<div class="jumbotron google-font">
  <h1 class="text-center">Your Shopping Cart</h1>
</div>

<div class="row">
  <table class="table google-font">
    <thead>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th class="remove-mob">Sub total</th>
    </thead>
    <tbody>
      <% @cart_products_with_qty.each do |array| %>
        <% product = array[0] %>
        <% qty = array[1] %>
        <tr>
          <td class="align-middle"><%= product.name %></td>
          <td class="align-middle">£ <%= product.price %></td>
          <td class="align-middle"><%= qty %></td>
          <td class="align-middle remove-mob">£ <%= product.price * qty.to_i %></td>
          <td class="align-middle cart-button">
            <%= link_to '+', add_to_cart_path(product), method: :put, class: "btn btn-primary btn-sm" %>
            <%= link_to '-', remove_one_cart_path(product), method: :put, class: "btn btn-warning btn-sm" %>
            <%= link_to 'Remove', remove_from_cart_path(product), method: :put, class: "btn button-maroon" %>
          </td>
        </tr>
      <% end %>
      <tr class="font-weight-bold card-footer mt-1">
         <% if @cart_products_with_qty.present? %>
            <td colspan="3">
              <h5>Total</h5>
            </td>
          <div>
            <td>
              <h5><span class="mr-1">£</span><%= @cart_total %></h5>
            </td>
          <% else %>
            <h4 class="mx-auto">You have no items in the cart</h4>
          <% end %>
          </div>

        </tr>
    </tbody>
  </table>
    <div class="links-mobile google-font">
      <%= link_to "Checkout", new_transaction_path, class: "btn button-maroon" unless current_user.get_cart_products_with_qty.blank? %>
      <%= link_to "Check Your Delivery address", user_path(current_user), class: "btn button-maroon" %>
      <%= link_to "Continue Shopping", products_path, class: "btn button-maroon ml-2" %>
    </div>
</div>