config/routes.rb
Rails.application.routes.draw do
 
  get 'sales/index'
  get 'sales/show'
  devise_for :users
  root 'pages#home'
  # root :to => 'products#index'
  

  resources :users do 
    resource :profile
    resources :orders, only: [:index, :show]
    resources :users, only: [:show, :index]
  end
  # resources :users, only: [:show, :index]
  resources :profiles, only: [:index, :show, :create]
  resources :products
  get 'my_products', to: 'products#my_products' 
  get 'search_product', to: 'products#search'
  resources :categories
  resources :orders
  #resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]
  
  get "*path", to: redirect('/')
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories
  has_many :products, through: :product_categories
  validates_uniqueness_of :name

  mount_uploader :picture, PictureUploader

  def picture_size 
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5mb")
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new, :edit, :update, :destroy]
  def index 
    @categories = Category.all
  end
  
  def new 
    @category = Category.new
  end

  def create 
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category added!"
      redirect_to categories_path
    else
      flash[:alert] = "#{@category.errors.full_messages.pop}"
      render 'categories/new'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @products = @category.products.all
  end

  def edit 
    @category = Category.find(params[:id])
  end

  def update 
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated!"
      redirect_to categories_path
    else
      flash[:alert] = "#{@category.errors.full_messages.pop}"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category removed!"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :picture)
  end

  def require_admin 
    if !( current_user.admin?)
      flash[:alert] = "You cannot perform this action"
      redirect_to products_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-maroon google-font ml-1" %>

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-8 offset-2">
    <%= form_with(model: @category, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :picture, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary mt-1"%>
        <%= link_to "All Categories", categories_path, class: "btn btn-success mt-1" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_listing.html.erb
<% obj.each do |product| %>
    <div class="card ml-3 mt-3 choose">
      <div class="card-body" >
          <div class="card-title">
            <p class="product-title google-font"> <%= product.name %> </p>
            <p><%= image_tag product.picture.url (:thumb) if product.picture?  %></p>
          </div>
          <div class="card-text google-font">
              <p><small>£</small> <%= product.price %></p>
          </div>
            <p> 
          <%= link_to "View / Order", product_path(product), class: "btn button-maroon google-font" %> 
          <% if current_user && current_user.admin? %>
            <%= link_to "Edit", edit_product_path(product), class: "btn btn-outline-warning google-font" %> 
            <%= link_to "Delete", product_path(product), class: "btn btn-outline-danger google-font", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
          <% if product.categories.any? %>
            <p class="text-center object-color google-font"><span class="object-color">Category: </span><%= render product.categories %></p>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1 class="jumbotron text-cennter">Edit Category</h1>

<%= render "categories/form" %>

app/views/categories/index.html.erb
<h1 class="jumbotron text-center google-font">
   Categories 
   <% if current_user && current_user.admin %>
      <%= link_to "Create new category", new_category_path, class: "btn btn-success btn-sm" %>
   <% end %>
   
</h1>

<div class="row">
     <%#= render 'shared/product', collection: @products %>
     <% unless @categories.count < 1 %>
         <% @categories.each do |cat| %>
            <div class="card choose ml-3 mb-3">
               <div class="card-body">
                  <div class="card-title">
                     <h4 class="text-center google-font"><strong><%= cat.name %></strong> </h4>
                     <p class="text-center"><%= image_tag cat.picture.url (:thumb) if cat.picture?  %></p>
                  </div>
                  <div class="card-body">
                     <%= link_to 'View category', category_path(cat), class: "btn button-maroon google-font btn-sm mt-1" %>
                     <% if current_user && current_user.admin %>
                        <%= link_to 'Edit category', edit_category_path(cat), class: "btn btn-warning google-font btn-sm mt-1" %>
                        <%= link_to 'Delete category', category_path(cat), method: :delete, class: "btn btn-danger google-font btn-sm mt-1" %>
                     <% end %>
                  </div>
               </div>
            </div>
      <% end %>
     <% else %>
      <div class="card-body">
         <h4 class="text-center google-font">There are no Categories Listed</h4>
      </div>
     <% end %>
     
  </div>

app/views/categories/new.html.erb
<h1 class="jumbotron text-cennter google-font">New Category</h1>

<%= render "categories/form" %>

app/views/categories/show.html.erb
<h1 class="jumbotron text-center google-font mt-2">
  <p>Category: <%= @category.name %></p>
  <%= link_to 'All Products', products_path, class: "btn button-maroon " %>
  <%= link_to 'All Categories', categories_path, class: "btn button-maroon " %>
</h1>

<div class="row">
  <%= render "categories/listing", obj: @category.products%>
</div>