config/routes.rb
Rails.application.routes.draw do
 
  get 'sales/index'
  get 'sales/show'
  devise_for :users
  root 'pages#home'
  # root :to => 'products#index'
  

  resources :users do 
    resource :profile
    resources :orders, only: [:index, :show]
    resources :users, only: [:show, :index]
  end
  # resources :users, only: [:show, :index]
  resources :profiles, only: [:index, :show, :create]
  resources :products
  get 'my_products', to: 'products#my_products' 
  get 'search_product', to: 'products#search'
  resources :categories
  resources :orders
  #resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]
  
  get "*path", to: redirect('/')
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orders
  has_many :users, through: :orders

  mount_uploader :picture, PictureUploader

  def picture_size 
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5mb")
    end
  end

  def self.matches(field_name, param) 
    where("#{field_name} ilike ?", "%#{param}%")
  end

  def self.search(param)
    param.strip!
    to_send_back = (name_matches(param) + description_matches(param) + price_matches(param)).uniq
    return nil unless to_send_back
    to_send_back 
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.description_matches(param)
    matches('description', param)
  end

  def self.price_matches(param)
    matches('cast(price as text)', param)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :require_admin, only: [:new, :edit, :update, :destroy]
  around_action :catch_not_found

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      # @category_array = params.dig(:product, :category_ids)
      # @category_array.each do |cat|
      #   @category = Category.find(cat)
      #   @product.categories << @category
      # end
      flash[:notice] = "Product added!"
      redirect_to products_path
    else
      flash[:notice] = "Product can't be blank!"
      render 'products/new'
    end
  end

  def show 
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      # @product.product_categories.destroy_all
      # @category_array = params.dig(:product, :category_ids)
      # @category_array.each do |cat|
      #   @category = Category.find(cat)
      #   @product.categories << @category
      # end
      flash[:notice] = "Product updated!"
      redirect_to products_path
    else
      puts @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    flash[:notice] = "Product removed!"
    redirect_to products_path
  end

  def search
    if params[:product].present?
      @products = params[:product].present?
      @products = Product.search(params[:product])
      if @products && @products.count > 0
        respond_to do |format|
        format.js { render partial: 'shared/searchresult' }
      end
      else
        respond_to do |format|
          flash.now[:unsucessful] = "Item not found"
          format.js { render partial: 'shared/searchresult' }
          end
        end
      else
        respond_to do |format|
        flash.now[:unsucessful] = "Please enter a Product name or description to search"
        format.js { render partial: 'shared/searchresult' }
      end
    end
  end


  private

    def product_params
      params.require(:product).permit(:name, :description, :price, :picture, category_ids: [])
    end

    def require_admin 
      if !( current_user.admin?)
        flash[:alert] = "You cannot perform this action"
        redirect_to products_path
      end
    end

    def catch_not_found
      yield
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Item not found"
      redirect_to root_url
    end

    # def extension_allowlist
    #   %w(jpg jpeg gif png)
    # end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-8 offset-2">
    <%= form_with(model: @product, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :picture, class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :category, class:"form-label float-left" %>
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
          {prompt: "Select a Category below (It can be empty)"}, {multiple: true, class: "custom-select form-decoration"}) %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary"%>
      </div>
      <%= link_to 'Back to Products List', products_path, class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
   $('#product_picture').bind('change', function() {
     var size_in_megabytes = this.files[0].size/1024/1024;
     if (size_in_megabytes > 5) {
       alert('Maximum file size is 5MB. Please choose a smaller file.');
     }
   });
 </script>

app/views/products/edit.html.erb
<h1 class="jumbotron text-center">Edit Product</h1>

<%= render "products/form" %>

app/views/products/index.html.erb
<div class="jumbotron google-font text-center">
   <h1 class="">Products List</h1>
   <% if current_user && current_user.admin? %>
      <%= link_to "Create new Product", new_product_path, class: "btn button-maroon but1-mob" %>
      <%= link_to "Categories", categories_path, class: "btn button-maroon but1-mob" %>
      <%= link_to "Create new Category", new_category_path, class: "btn button-maroon ml-1" %>
   <% end %>
</div>
   <!-- Search Results -->
   <div id="search-results">
   </div>
   <!-- Displays Product Listing -->
  <div class="row">
     <%= render 'shared/listing' %>
  </div>

app/views/products/new.html.erb
<h1 class="jumbotron text-center">New Product</h1>

<%= render "products/form" %>

app/views/products/show.html.erb
<div id="search-results"></div>
<div class="jumbotron google-font text-center mt-3">
  <h1><%= @product.name.capitalize %></h1>
  </div>
  <div class="row google-font">
    <div class="col">
    <div class="card card-body ">
      <p> <%= simple_format @product.description %></p>
      <h4 class="">£ <%= @product.price %></h4>
    </div>
  </div>
  
  <div class="col">
    <div class="card card-body text-center">
      <p><%= image_tag @product.picture.url if @product.picture? %> </p>
    </div>
  </div>
  </div>


<div class="card google-font">
  <div class="card-body">
      <% if current_user %>
        <%= link_to "Add to cart", add_to_cart_path(@product), method: :put, class: "btn button-maroon btn-sm ml-3" %></p>
      <% else %>
        <p class="show-warning">To continue to order please Login or Create your account</p>
      <% end %>
    <% if @product.categories.any? %>
      <p class="">Categories: <%=  render @product.categories %></p>
    <% end %>
  </div>
  <div class="card-body product-options">
    <%= link_to 'In Store', root_path, class: "btn button-maroon " %>
    <%= link_to 'Categories', categories_path, class: "btn button-maroon " %>
    <% if current_user && current_user.admin? %>
      <%= link_to 'Products (Admin)', products_path, class: "btn btn-primary" %>
      <%= link_to 'Edit Product', edit_product_path(@product), class: "btn btn-primary" %>
      <%= link_to 'Delete Product', product_path(@product),  method: :delete, class: "btn btn-danger" %>
    <% end %>
    
  </div>
</div>