config/routes.rb
Rails.application.routes.draw do
 
  get 'sales/index'
  get 'sales/show'
  devise_for :users
  root 'pages#home'
  # root :to => 'products#index'
  

  resources :users do 
    resource :profile
    resources :orders, only: [:index, :show]
    resources :users, only: [:show, :index]
  end
  # resources :users, only: [:show, :index]
  resources :profiles, only: [:index, :show, :create]
  resources :products
  get 'my_products', to: 'products#my_products' 
  get 'search_product', to: 'products#search'
  resources :categories
  resources :orders
  #resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]
  
  get "*path", to: redirect('/')
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>" >
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
      </div>
    <% end %>
  </div >
</div >

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark navbar-expand-md bg-maroon justify-content-between google-font">
   <small class="navbar footer-text mx-auto text-white">Created by <%= link_to "Vincent Walker", "https://vincethewalker.herokuapp.com", target: "_blank", class: "footer-logo text-white ml-1 mr-1" %> 2021</small>
 </nav>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<!-- And -->

<% if alert %>
  <div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
    </button>
    <%= alert %>
  </div>
<% end %>

<% if info %>
  <div class='alert alert-light brand'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
    </button>
    <%= info %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-maroon">
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%# <h4 class="mobile-title-object" style="color: white;">My Wines</h4> %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item dropdown mt-1">
        <span class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= link_to current_user.name, "#", class: "nav-text text-decoration-none google-font mobile-only" %> <%= "(Admin)" if current_user.admin?  %>
        </span>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Add a Delivery address", new_user_profile_path(current_user), class: "nav-link  google-font drop-object mb-2" unless current_user.profile %>
            <%= link_to (current_user.name),  user_path(current_user), class: "nav-link  google-font drop-object mb-2" if current_user.profile %>
            <%= link_to "View all Categories", categories_path, class: "nav-link google-font drop-object mb-2" %> 
            <%= link_to "Change Delivery Details", edit_user_profile_path(current_user), class: "nav-link  google-font drop-object mb-2" if current_user.profile %>
            <%= link_to "Change Account Details", edit_user_registration_path(current_user), class: "nav-link google-font  drop-object mb-2" %>
            <%#= link_to "Create A New User", new_user_registration_path, class: "nav-link google-font  drop-object mb-2" if current_user.admin?  %>
            <%#= link_to "Close your Account", "#", class: "nav-link google-font drop-object mb-2" %>
            <% if current_user.orders.count > 0 %>
              <%= link_to "Orders", user_orders_path(current_user), class: "nav-link google-font drop-object mb-2" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link google-font mobile-only" %>
          </div>
          <% else %>
          <div class="flex">
            <%= link_to "Create an account", new_user_registration_path, class: "nav-text text-decoration-none google-font" %> 
            <%= link_to "/ Log in", user_session_path, class: "nav-text ml-1 text-decoration-none google-font" %>
          </div>
        </li>
      <% end %>
        <li class="nav-item">
          <% if current_user.try(:admin?) %>
          <div class="dropdown mt-1">
              <span class="nav-link dropdown-toggle" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= link_to "My Wines", root_path, class: "nav-text text-decoration-none google-font text-center center-mark mobile-only" %>
              </span>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Product Range", products_path, class: "nav-link google-font drop-object mb-2" %>
                <%= link_to "Categories", categories_path, class: "nav-link google-font drop-object mb-2" %>
                <%= link_to "View Orders", orders_path, class: "nav-link google-font  drop-object mb-2" %>
                <%= link_to "Sales", sales_index_path(current_user), class: "nav-link google-font drop-object mb-2" %>
                <%= link_to "Customers", profiles_path, class: "nav-link google-font drop-object mb-2" %>
                <%= link_to "Users", users_path, class: "nav-link google-font drop-object" %>
              </div>
            </div>
            </button>
          <% end %>
        </li>
      </ul>
    <!--<form class="form-inline my-2 my-lg-0">
        <%#= render 'shared/searchform' %>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success button-maroon my-2 my-sm-0" type="submit">Search</button>
      </form>  -->
      <ul class="navbar-nav">
      <%# if !current_user %>
        <li class="nav-item mt-2"><%= link_to "Home", root_path, class: "nav-text  text-decoration-none google-font" %></li>
        <li class="nav-item mt-2 ml-2">
        <% if current_user %>
          <%= link_to ' (' + "#{current_user.cart_count}" + ')', cart_path , class: "nav-text text-decoration-none google-font" %>
        <% end %>
      </li>
      <%# end %>
      <li class="nav-item mt-1">
        <%= render 'shared/searchform' %>
        <%# if current_user %>
          <%#= link_to 'View all categories', categories_path, class: "badge badge-maroon google-font nav-cart mobile-only" %>
        <%# else %>
          <%#= link_to "Create your account", new_user_registration_path, data: { turbolinks: false }, class: "badge badge-maroon google-font nav-cart " %>
        <%# end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Wines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>